name: Build
on: [push]
jobs:
    build: 
        name: Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout code
            - name: Setup dotnet 
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '6.x'
            - name: Setup MSBuild Path
              uses: microsoft/Setup-MSBuild@v1.0.3
            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.5
            - name: Query nuget folders(figure out where nunit.consolerunner is stored)
              run: nuget locals global-packages -list
            - name: Restore NuGet Packages
              run: nuget restore TimeSeriesAnalysis.sln
            - name: Build 
              run: dotnet build TimeSeriesAnalysis.sln -c Release
            - name: dotnet pack to create *.nupkg file build artifact
              run: dotnet pack TimeSeriesAnalysis.sln -c Release --include-symbols -p:SymbolPackageFormat=snupkg --include-source
            - name: nuget.pkg.github.com  set API key
              run: nuget setapikey ${{secrets.NUGET_API_KEY}} -source https://nuget.pkg.github.com/equinor/
            - name: nuget.pkg.github.com publish 
              run: nuget push bin\Release\*.nupkg -source https://nuget.pkg.github.com/equinor/ -SkipDuplicate
            - name: api.nuget.org set API key
              run: nuget setapikey ${{secrets.NUGET_ORG_API_KEY}} -source https://api.nuget.org/v3/index.json
            - name: api.nuget.org publish 
              run: nuget push bin\Release\*.nupkg -source https://api.nuget.org/v3/index.json -SkipDuplicate
              
                
