name: Build
on: [push]
jobs:
    build: 
        name: Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout code
            - name: Setup MSBuild Path
              uses: microsoft/Setup-MSBuild@v1.0.3
            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.5
            - name: Query nuget folders(figure out where nunit.consolerunner is stored)
              run: nuget locals global-packages -list
            - name: Restore NuGet Packages
              run: nuget restore TimeSeriesAnalysis.sln
            - name: Build 
              run: msbuild TimeSeriesAnalysis.sln /p:Configuration=Debug
            - name: Publish
              run: nuget setapikey ${{secrets.NUGET_API_KEY}} -source https://nuget.pkg.github.com/equinor/
              run: nuget push bin\Debug\*.nupkg -source https://nuget.pkg.github.com/equinor/ -SkipDuplicate
            #- name: Publish
            #  uses: rohith/publish-nuget@v2
            #  with:
            #    PROJECT_FILE_PATH: TimeSeriesAnalysis.csproj
            #    TAG_COMMIT: true
            #    TAG_FORMAT: v*
            #    NUGET_KEY: ${{secrets.NUGET_API_KEY}}
            #    NUGET_SOURCE: https://nuget.pkg.github.com/equinor/
                