name: docfx
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate and publish the docs
    outputs:
      output1: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v1
      name: Checkout code
    - uses: nunit/docfx-action@v2.4.0
      name: Build Documentation
      with:
        args: docfx.json
    - uses: actions/upload-artifact@v4
      with: 
        name: github-pages
        path: docs
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      actions: read     # to read the artifact made by build
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on:  ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.output1}}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with: 
          overwrite: true