name: workflow
on: [push]
jobs:
    build: 
        name: Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout code
            - name: Setup MSBuild Path
              uses: microsoft/Setup-MSBuild@v1.0.3
            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.5
            - name: Query nuget folders
              run: nuget locals  
            - name: Restore NuGet Packages
              run: nuget restore TimeSeriesAnalysis.sln
            - name: Build 
              run: msbuild TimeSeriesAnalysis.sln /p:Configuration=Debug
            - name: Test
              run: %userprofile%\.nuget\packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe \bin\Debug\TimeSeriesAnalysis.dll